COMPOSER_NAMESPACE = 'org.synerzip.firstcomposer'
APP_BASE_URL = 'http://localhost:3000'
ADMIN_API_BASE_URL = 'http://localhost:3001/api'
USER_API_BASE_URL = APP_BASE_URL + '/api'
GITHUB_SIGNIN_URL = APP_BASE_URL + '/auth/github'
GITHUB_SIGNOUT_URL = APP_BASE_URL + '/auth/logout'
USER_ROLE = 'USER'
IT_ADMIN_ROLE = 'IT_ADMIN'
PRODUCT_TYPE = [ 'LAPTOP', 'DESKTOP', 'MOBILE']

AVAILABLE = 'AVAILABLE'
ISSUED = 'ISSUED'

PLACED = 'PLACED'
FULFILLED = 'FULFILLED'